# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Um lögstofuna
    url: '#about'
    weight: 10
  - name: Hafa samband
    url: '#contact'
    weight: 20
  - name: Bóka fund
    url: '#booking'
    weight: 30